"""
shap_helper.py — SHAP HTML visualisation helper
Imported by app.py to render token-level heatmaps in Streamlit.
Generated by notebook_04_explainability.ipynb.
"""

def shap_to_html(text: str, shap_values, review_idx: int = 0,
                 class_idx: int = 1) -> str:
    """
    Convert SHAP token values to an HTML heatmap string.

    Args:
        text        : Original review text
        shap_values : Output of shap.Explainer()(texts)
        review_idx  : Which review in the batch (default 0)
        class_idx   : 0=NEGATIVE, 1=POSITIVE (default 1)

    Returns:
        HTML string — render with st.markdown(html, unsafe_allow_html=True)
    """
    import numpy as np

    tokens = shap_values.data[review_idx]
    values = shap_values.values[review_idx, :, class_idx]

    max_abs = max(abs(values.max()), abs(values.min()), 1e-6)
    norm    = values / max_abs

    parts = []
    for token, val, norm_val in zip(tokens, values, norm):
        if token in {"[CLS]", "[SEP]", "[PAD]"}:
            continue
        display_token = token.replace("##", "")
        opacity = min(abs(norm_val) * 0.85 + 0.1, 0.9)
        if norm_val > 0:
            r, g, b = 46, 158, 107
        else:
            r, g, b = 231, 76, 60
        bg_colour = f"rgba({r},{g},{b},{opacity:.2f})"
        tooltip   = f"SHAP: {val:+.4f}"
        parts.append(
            f'<span title="{tooltip}" style="'
            f'background-color:{bg_colour};padding:2px 4px;margin:1px;'
            f'border-radius:3px;font-family:monospace;font-size:13px;'
            f'display:inline-block;">{display_token}</span>'
        )

    body   = '<div style="line-height:2.4;">' + " ".join(parts) + '</div>'
    legend = (
        '<div style="margin-top:10px;font-size:12px;color:#666;">' 
        '<span style="background:rgba(46,158,107,0.6);padding:2px 6px;border-radius:3px;">' 
        'positive signal</span>&nbsp;&nbsp;' 
        '<span style="background:rgba(231,76,60,0.6);padding:2px 6px;border-radius:3px;">' 
        'negative signal</span>&nbsp;&nbsp;' 
        'Hover each token for exact SHAP value' 
        '</div>'
    )
    return f'<div style="padding:8px;">{body}{legend}</div>'
